[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "v2sim"
version = "1.3.0"
dependencies = [
    "libsumo",
    "numpy",
    "matplotlib",
    "feasytools>=0.1.0",
    "fpowerkit>=0.3.3",
    "pyproj",
    "requests",
    "ordered-set",
]
requires-python = ">= 3.8"
readme = {file = "README.md", content-type = "text/markdown"}
license = "BSD-3-Clause"
description = "V2Sim: An Open-Source Microscopic V2G Simulation Platform in Urban Power and Transportation Network"

[project.optional-dependencies]
v2g = [
    "ecos",
    "cvxpy",
]

[project.urls]
Homepage = "https://github.com/fmy-xfk/v2sim"
Documentation = "https://github.com/fmy-xfk/v2sim/wiki"
Repository = "https://github.com/fmy-xfk/v2sim.git"
Issues = "https://github.com/fmy-xfk/v2sim/issues"